let editingId=null, adminProducts=[];
const A=(u,o)=>fetch(u,o).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Error");return d});
async function boot(){const m=await A("/api/admin/me");if(m.authenticated)showDash();else login.style.display="grid"}
async function login(){try{await A("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});showDash()}catch(e){alert(e.message)}}
async function logout(){await A("/api/admin/logout",{method:"POST"});location.reload()}
function showDash(){login.classList.add("hidden");dashboard.classList.remove("hidden");showTab("overview")}
async function showTab(t){tabTitle.textContent=t[0].toUpperCase()+t.slice(1);if(t==="overview")return overview();if(t==="products")return productsTab();if(t==="orders")return ordersTab();if(t==="settings")return settingsTab()}
async function overview(){const s=await A("/api/admin/stats");content.innerHTML=`<div class="statGrid"><div class="stat">Omzet<b>${fmt(s.revenue)}</b></div><div class="stat">Pesanan<b>${s.orders}</b></div><div class="stat">Terjual<b>${s.sold}</b></div><div class="stat">Stok Menipis<b>${s.low_stock}</b></div></div>`}
async function productsTab(){adminProducts=await A("/api/admin/products");content.innerHTML=`<div style="margin-bottom:15px"><button class="btn primary" onclick="openProduct()">+ Tambah Produk</button></div><div class="tableWrap"><table class="table"><tr><th>Produk</th><th>Harga</th><th>Stok</th><th>Aksi</th></tr>${adminProducts.map(p=>`<tr><td>${p.name}<br><small>${p.brand} • ${p.sku}</small></td><td>${fmt(p.sale_price||p.price)}</td><td>${p.stock}</td><td><div class="rowActions"><button class="smallBtn" onclick="openProduct(${p.id})">Edit</button><button class="smallBtn" onclick="delProduct(${p.id})">Hapus</button></div></td></tr>`).join("")}</table></div>`}
function openProduct(id){editingId=id||null;productModal.classList.add("show");productForm.reset();formTitle.textContent=id?"Edit Produk":"Tambah Produk";if(id){const p=adminProducts.find(x=>x.id===id);for(const [k,v] of Object.entries(p)){if(productForm.elements[k])productForm.elements[k].value=Array.isArray(v)?v.join(v.includes("|")?"|":","):v}}}
function closeProduct(){productModal.classList.remove("show")}
async function saveProduct(e){e.preventDefault();const f=new FormData(productForm),p=Object.fromEntries(f.entries());p.price=+p.price;p.sale_price=p.sale_price?+p.sale_price:null;p.stock=+p.stock;p.discount=+p.discount||0;p.rating=5;if(photo.files[0]){const fd=new FormData();fd.append("image",photo.files[0]);const u=await A("/api/admin/upload",{method:"POST",body:fd});p.image=u.url}try{await A(editingId?"/api/admin/products/"+editingId:"/api/admin/products",{method:editingId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});closeProduct();productsTab()}catch(e){alert(e.message)}}
async function delProduct(id){if(!confirm("Hapus produk ini?"))return;await A("/api/admin/products/"+id,{method:"DELETE"});productsTab()}
async function ordersTab(){const o=await A("/api/admin/orders");content.innerHTML=`<div class="tableWrap"><table class="table"><tr><th>#</th><th>Pelanggan</th><th>Total</th><th>Status</th><th>Tanggal</th></tr>${o.map(x=>`<tr><td>#${x.id}</td><td>${x.customer_name}<br>${x.phone}</td><td>${fmt(x.total)}</td><td><select onchange="status(${x.id},this.value)">${["Baru","Diproses","Dikirim","Selesai","Dibatalkan"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></td><td>${x.created_at}</td></tr>`).join("")}</table></div>`}
async function status(id,s){await A("/api/admin/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:s})})}
async function settingsTab(){const s=await A("/api/settings");content.innerHTML=`<form onsubmit="saveSettings(event)" style="max-width:650px;background:#fff;padding:25px;border-radius:18px"><input name="store_name" value="${s.store_name||""}" placeholder="Nama toko"><input name="whatsapp" value="${s.whatsapp||""}" placeholder="WhatsApp format 628..."><input name="address" value="${s.address||""}" placeholder="Alamat"><input name="hours" value="${s.hours||""}" placeholder="Jam buka"><input name="instagram" value="${s.instagram||""}" placeholder="Instagram"><input name="payment_methods" value="${s.payment_methods||""}" placeholder="Metode pembayaran"><input name="hero_title" value="${s.hero_title||""}" placeholder="Judul hero"><textarea name="hero_subtitle" placeholder="Subjudul">${s.hero_subtitle||""}</textarea><button class="btn primary">Simpan Pengaturan</button></form>`}
async function saveSettings(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.target));await A("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});alert("Pengaturan tersimpan")}
async function refresh(){showTab("overview")}function fmt(n){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
boot();
