let products=[], cart=JSON.parse(localStorage.getItem("mila_cart")||"[]"), activeBrand="";
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
async function api(url,opt){const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw Error(d.error||"Terjadi kesalahan");return d}
async function init(){const s=await api("/api/settings");document.title=s.store_name;document.querySelector(".brand").innerHTML=s.store_name.replace(/ (.*)/,"<span> $1</span>");heroTitle.textContent=s.hero_title;heroSub.textContent=s.hero_subtitle;loadProducts();updateCart()}
async function loadProducts(){const q=document.getElementById("search").value;products=await api("/api/products?"+new URLSearchParams({q,brand:activeBrand}));renderFilters();renderProducts()}
function renderFilters(){const brands=[...new Set(products.map(p=>p.brand))];filters.innerHTML=`<button class="chip ${!activeBrand?"active":""}" onclick="activeBrand='';loadProducts()">Semua</button>`+brands.map(b=>`<button class="chip ${activeBrand===b?"active":""}" onclick="activeBrand='${b}';loadProducts()">${b}</button>`).join("")}
function renderProducts(){document.getElementById("products").innerHTML=products.length?products.map(p=>`<article class="card"><div class="pic"><img src="${p.image||'https://placehold.co/800x600?text=Phone'}" alt="${p.name}"></div><div class="cardBody"><div class="brandTxt">${p.brand} • ${p.condition}</div><h3>${p.name}</h3><div class="price">${rupiah(p.sale_price||p.price)} ${p.sale_price?`<span class="old">${rupiah(p.price)}</span>`:""}</div><div class="stock">★ ${p.rating} • Stok ${p.stock}</div><button class="btn primary add" onclick="addCart(${p.id})">Tambah ke Keranjang</button></div></article>`).join(""):`<p>Produk tidak ditemukan.</p>`}
function addCart(id){const p=products.find(x=>x.id===id);const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:p.sale_price||p.price,qty:1});persist();updateCart()}
function persist(){localStorage.setItem("mila_cart",JSON.stringify(cart))}
function updateCart(){cartCount.textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openCart(){cartModal.classList.add("show");renderCart()}function closeCart(){cartModal.classList.remove("show")}
function renderCart(){cartItems.innerHTML=cart.length?cart.map((x,i)=>`<div class="cartRow"><div><b>${x.name}</b><div>${rupiah(x.price)}</div></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button>${x.qty}<button onclick="changeQty(${i},1)">+</button></div></div>`).join(""):"<p>Keranjang masih kosong.</p>";cartTotal.textContent=rupiah(cart.reduce((a,x)=>a+x.price*x.qty,0))}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);persist();updateCart();renderCart()}
async function checkout(){if(!cart.length)return alert("Keranjang kosong");const customer_name=customer.value.trim(),phone=window.phone.value.trim(),address=window.address.value.trim();if(!customer_name||!phone)return alert("Isi nama dan nomor WhatsApp");try{const o=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name,phone,address,items:cart.map(x=>({id:x.id,qty:x.qty}))})});const s=await api("/api/settings");const msg=`Halo ${s.store_name}, saya ingin order #${o.order_id}.%0A%0ANama: ${encodeURIComponent(customer_name)}%0AHP: ${encodeURIComponent(phone)}%0AAlamat: ${encodeURIComponent(address)}%0ATotal: ${encodeURIComponent(rupiah(o.total))}`;cart=[];persist();updateCart();window.open(`https://wa.me/${s.whatsapp}?text=${msg}`,"_blank");closeCart();loadProducts()}catch(e){alert(e.message)}}
init();
